# docker-compose.yml 
version: '3.9'

services:
    app:
      build: .
      container_name: app
      restart: unless-stopped
      ports:
        - ${APP_PORT}:${APP_PORT}
      volumes:
        - ./static:/opt/static
      networks:
        - postgres-net
        - localnet
    
    migrate-up:
      image: migrate/migrate
      container_name: migrate-up
      volumes:
        - ${MIGRATIONS_HOST_PATH:-./migrations}:/migrations
      command:
         [
          "-path",
          "/migrations",
          "-database",
          "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable",
          "up"
        ]
      networks:
        - postgres-net

networks:
  postgres-net:
    external: true
    name: postgres-net

  localnet:
    external: true
    name: localnet